# .github/workflows/svk-scraper-simple.yml
name: SVK Power Data Scraper (Simple)

on:
  #schedule:
    # Run at 06:00 UTC every day
  #  - cron: '0 6 * * *'
  
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Number of days to scrape'
        required: false
        default: '3'

# Grant necessary permissions
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas beautifulsoup4
    
    - name: Create directory structure
      run: |
        mkdir -p data logs reports
    
    - name: Run scraper
      env:
        DISPLAY: :99
        GITHUB_ACTIONS: true
      run: |
        # Start virtual display
        sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        
        # Run the scraper
        python scripts/github_actions_runner.py daily || echo "Scraper completed with warnings"
    
    - name: Check if data was collected
      id: check_data
      run: |
        if [ -f "data/svk_master_data.csv" ]; then
          echo "data_exists=true" >> $GITHUB_OUTPUT
          echo "✅ Data file exists"
          wc -l data/svk_master_data.csv
        else
          echo "data_exists=false" >> $GITHUB_OUTPUT
          echo "⚠️ No data file found"
        fi
    
    - name: Commit and push changes
      if: steps.check_data.outputs.data_exists == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Add data files
        git add data/*.csv || true
        git add data/*.json || true
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📊 Update SVK data - $(date +'%Y-%m-%d %H:%M')"
          git push
        fi
    
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-logs-${{ github.run_number }}
        path: |
          logs/*.log
          error_screenshot.png
        retention-days: 7
        if-no-files-found: ignore
